var oMenu_root = new Menu();
var oMenu_1 = oMenu_root.CreateLink();
oMenu_1.displayHtml = "Home";
oMenu_1.href = NTK_RootPath + "Menu_menu_1.html";
oMenu_root.AddItem(oMenu_1);
var oMenu_2 = oMenu_root.CreateLink();
oMenu_2.displayHtml = "Contact Us";
oMenu_2.href = NTK_RootPath + "Menu_menu_2.html";
oMenu_root.AddItem(oMenu_2);
var oMenu_3 = oMenu_root.CreateLink();
oMenu_3.displayHtml = "About Us";
oMenu_3.href = NTK_RootPath + "Menu_menu_3.html";
oMenu_root.AddItem(oMenu_3);
oMenu_root.SetOrientation("v");
//oMenu_root.SetSubMenuImage("images/flyout_arrow.gif", 4, 7);
oMenu_root.SetSize(150, 20);
