//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MisbunEntities : DbContext
    {
        public MisbunEntities()
            : base("name=MisbunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Albem> Albems { get; set; }
        public DbSet<Artost> Artosts { get; set; }
        public DbSet<Cert> Certs { get; set; }
        public DbSet<Genru> Genrus { get; set; }
        public DbSet<Ordir> Ordirs { get; set; }
        public DbSet<OrdirDatail> OrdirDatails { get; set; }
    }
}
