//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int RekodId { get; set; }
        public string CartaId { get; set; }
        public int BannerId { get; set; }
        public int Count { get; set; }
        public System.DateTime Tarikh { get; set; }
    }
}
