//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPesan
    {
        public int DetailPesanId { get; set; }
        public int PesanId { get; set; }
        public int BannerId { get; set; }
        public int Kuantiti { get; set; }
        public decimal UnitHarga { get; set; }
    }
}
