//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MisbunEntities : DbContext
    {
        public MisbunEntities()
            : base("name=MisbunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Affiliate> Affiliates { get; set; }
        public DbSet<Banner> Banners { get; set; }
        public DbSet<Carta> Cartas { get; set; }
        public DbSet<DetailPesan> DetailPesans { get; set; }
        public DbSet<Kategori> Kategoris { get; set; }
        public DbSet<Pesan> Pesans { get; set; }
    }
}
